language: node_js
node_js:
 - "node"
cache: yarn

install:
  - yarn install

script:
  - yarn test
  - yarn build

after_success: yarn run test:coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
